# Generated by Django 6.0.6 on 2026-06-21 12:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=cloudinary.models.CloudinaryField(
                default="default", max_length=255, verbose_name="image"
            ),
        ),
    ]
